[package]
name = "hello-world"
version = "0.2.0"
edition = "2021"

[dependencies]
webatui = { path = "../../" }
ratatui = { version = "0.25", default-features = false, features = ["all-widgets"] }
yew = "0.21"
