name: Webatui CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable
          components: rustfmt
          targets: wasm32-unknown-unknown
      - uses: actions/checkout@v4
      - name: Fetch Trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          version: 'latest'
      - run: cargo build --verbose
      - run: cargo test --verbose
      - run: wget -qO- https://github.com/thedodd/trunk/releases/download/v0.16.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      - run: pwd >> $GITHUB_PATH
